export default [
    {
        "id" : "pj1",
        "name" : "국립생태원 10주년",
        "stack" : "HTML, CSS, Javascript, Jquery",
        "period" : "2023-09 ~ 2023-09",
        "desc" : "반응형 웹 사이트 구축",
        "link" : "https://www.nie.re.kr/nieAnn/main/main.do",
        "pcImg" : "/img/pj_nie_pc.jpg",
        "moImg" : "/img/pj_nie_m.jpg",
    },
    {
        "id" : "pj2",
        "name" : "부평구문화재단",
        "stack" : "HTML, CSS, Javascript, Jquery",
        "period" : "2023-01 ~ 2023-06",
        "desc" : "CMS 기반 반응형 웹 홈페이지 구축",
        "link" : "https://www.bpcf.or.kr/bpcf/main/main.do",
        "pcImg" : "/img/pj_bpcf_pc.jpg",
        "moImg" : "/img/pj_bpcf_m.jpg",
    },
    {
        "id" : "pj3",
        "name" : "손기정박물관",
        "stack" : "HTML, CSS, Javascript, Jquery",
        "period" : "2022-10 ~ 2023-01",
        "desc" : "CMS 기반 반응형 웹 홈페이지 구축 및 웹접근성 획득",
        "link" : "https://www.sonkeechung.com/sonkeechung/main/main.do",
        "pcImg" : "/img/pj_skj_pc.jpg",
        "moImg" : "/img/pj_skj_m.jpg",
    },
    {
        "id" : "pj4",
        "name" : "강남구청",
        "stack" : "HTML, CSS, Javascript, Jquery",
        "period" : "2022-08~2022-08",
        "desc" : "반응형 웹 리뉴얼 작업 및 웹접근성 획득",
        "link" : "https://www.gangnam.go.kr/main.do",
        "pcImg" : "/img/pj_gn1_pc.jpg",
        "moImg" : "/img/pj_gn1_m.jpg",
    },
    {
        "id" : "pj5",
        "name" : "강남구청 동주민센터",
        "stack" : "HTML, CSS, Javascript, Jquery",
        "period" : "2022-12 ~ 2022-12",
        "desc" : "반응형 웹 리뉴얼 작업",
        "link" : "https://www.gangnam.go.kr/center/main.do?office=3220049",
        "pcImg" : "/img/pj_gn2_pc.jpg",
        "moImg" : "/img/pj_gn2_m.jpg",
    },
    {
        "id" : "pj6",
        "name" : "공동체주택플랫폼",
        "stack" : "HTML, CSS, Javascript, Jquery",
        "period" : "2021-12 ~ 2022-04",
        "desc" : "CMS 기반 반응형 웹 홈페이지 구축 및 웹접근성 획득",
        "link" : "https://soco.seoul.go.kr/coHouse/main/main.do",
        "pcImg" : "/img/pj_co_pc.jpg",
        "moImg" : "/img/pj_co_m.jpg",
    },
    {
        "id" : "pj7",
        "name" : "인제 백중앙의료원",
        "stack" : "HTML, CSS, Javascript, Jquery",
        "period" : "2021-12 ~ 2022-06",
        "desc" : "CMS 기반 반응형 웹 홈페이지 구축",
        "link" : "https://www.paik.ac.kr/paik/user/main/view.do",
        "pcImg" : "/img/pj_paik_pc.jpg",
        "moImg" : "/img/pj_paik_m.jpg",
    },
    {
        "id" : "pj8",
        "name" : "2023 세종 올패스",
        "stack" : "HTML, CSS, Javascript, Jquery",
        "period" : "",
        "desc" : "세종문화회관 이벤트 페이지",
        "link" : "https://www.sejongpac.or.kr/portal/subMain/allPassFirst2023.do",
        "pcImg" : "/img/pj_sj3_pc.jpg",
        "moImg" : "/img/pj_sj3_m.jpg",
    },
    {
        "id" : "pj9",
        "name" : "2022 세종 여름시즌",
        "stack" : "HTML, CSS, Javascript, Jquery",
        "period" : "",
        "desc" : "반응형 웹페이지 제작",
        "link" : "https://season.sejongpac.or.kr/portal/season/main_2022.do",
        "pcImg" : "/img/pj_sj2_pc.jpg",
        "moImg" : "/img/pj_sj2_m.jpg",
    },
]